"""Added publication_date, language, reading_age to Book

Revision ID: 0d39ebebeb80
Revises: 2021f33cad92
Create Date: 2025-10-05 20:52:39.885282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d39ebebeb80'
down_revision = '2021f33cad92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reading_age', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('reading_age')
        batch_op.drop_column('language')
        batch_op.drop_column('publication_date')

    # ### end Alembic commands ###
